version: "3.9"
services:
  postgre:
    container_name: postrge
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=admin
    image: postgres:15.2
    volumes:
      - db-data:/var/lib/postgres
volumes:
  db-data: