version: "3.9"
services:
  web:
    build: .
    ports:
      - "80:80"
    depends_on:
      - postgre
  postgre:
    container_name: postrge
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=admin
    image: postgres:15.2
    volumes:
      - db-data:/var/lib/postgres
      - ./init:/docker-entrypoint-initdb.d      

volumes:
  db-data: